### ISSUE TITLE
能不能添加console ui

### ISSUE THREAD

**Issue by Huangyan0804** [Vi-brance/vscode-qlite#10]
提供像控制台一样的ui界面，现在的太大太明显了

**Comment by Vi-brance** [comment]
当前的UI其实还有部分功能没实现，因此在完善前可能不太会同时提供console界面，而且目前的UI是参考了开源的ui框架，你若是能提供console的聊天框架我也许能将其整合进去

ps：有这个打算，但我写的还不够熟练（太菜了
