### ISSUE TITLE
不支持CQ信息

### ISSUE THREAD

**Issue by cangSDARM** [Vi-brance/vscode-qlite#12]
https://github.com/Mrs4s/go-cqhttp/blob/master/docs/cqhttp.md

测试了 

[CQ:image,file=http://tva2.moyu.im/mw1024/005JUUMSgy1hcz0vfafe5g307n07bb2g.gif]

不起作用

vscode-qq 支持

**Comment by Vi-brance** [comment]
目前聊天界面功能的支持还不完善，我对输入框的实现逻辑是将文本或图片转换成消息链格式传递到服务器，服务器会将消息链解析成cq码格式发送，因此不支持在输入框输入cq码格式的消息传输
