### ISSUE TITLE
当前环境存在发现，为保障你的账号安全，暂时无法登录

### ISSUE THREAD

**Issue by jadelike-wine** [Vi-brance/vscode-qlite#15]
rt

**Comment by Vi-brance** [comment]
请详细描述你遇到的问题，否则我无法判断是依赖bug还是扩展bug

**Comment by jadelike-wine** [comment]
> 请详细描述你遇到的问题，否则我无法判断是依赖bug还是扩展bug

就扫码登陆的时候碰到的，手机端提示这个

**Comment by Vi-brance** [comment]
QQ协议更新后icqq暂时没有适配，已提issue，等稳定后应该会修复

**Comment by Vi-brance** [comment]
> QQ协议更新后icqq暂时没有适配，已提issue，等稳定后应该会修复

@jadelike-wine 收到作者的回复了，目前只有watch协议支持扫码登录，你先使用密码登录吧

**Comment by jadelike-wine** [comment]
> > QQ协议更新后icqq暂时没有适配，已提issue，等稳定后应该会修复
> 
> @jadelike-wine 收到作者的回复了，目前只有watch协议支持扫码登录，你先使用密码登录吧

密码登录也报错：
[禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Error Code: 45

**Comment by SaiyanGuo** [comment]
楼上+1，密码登录确实会报错，报错内容与上面发的一致。 @Vi-brance

**Comment by Vi-brance** [comment]
> 密码登录也报错：[禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Error Code: 45

是否尝试过用QQ直接登录，排查一下账号本身的问题
icqq那边也有相同问题，有人似乎通过清理账号的登录设备记录解决，你可以尝试一下

如果上述方法无解，我这边也在更新icqq最新版的扩展，下一版本会修复

**Comment by Vi-brance** [comment]
新版本已发布，若没有上述问题将关闭此issue

**Comment by jadelike-wine** [comment]
> 新版本已发布，若没有上述问题将关闭此issue

@SaiyanGuo @Vi-brance 安装最新版本后，现在通过密码登录，登录按钮短暂进入到“登陆中”字样，过一会又回到了“登录”字样，没有其他报错和其他反应......就登陆不了。在手机或PC上，这个QQ号是正常可以登录的

**Comment by jadelike-wine** [comment]
> 新版本已发布，若没有上述问题将关闭此issue
从releases上下载最新版本后，仍然无法登录，并有此报错

**Comment by Vi-brance** [comment]
@jadelike-wine 你在使用此扩展时通过`Ctrl`+`Shift`+`P`选择`打开webview开发人员工具`，将输出记录截下来，我看看问题在哪

**Comment by jadelike-wine** [comment]
> @jadelike-wine 你在使用此扩展时通过`Ctrl`+`Shift`+`P`选择`打开webview开发人员工具`，将输出记录截下来，我看看问题在哪
![image](https://github.com/Vi-brance/vscode-qlite/assets/46087189/aaa63d41-6bae-4ef6-8d8a-92f9fce5fe60)
@Vi-brance

**Comment by Vi-brance** [comment]
已经在向icqq的 [这个issue](https://github.com/icqqjs/icqq/issues/15) 寻求解决办法了，我这边暂时无能为力。

**Comment by juliansy** [comment]
同样问题。2023/5/12 16:45

**Comment by FreyLee** [comment]
5/17, 还是有同样的问题, 我用icqq把platform改成2是可以登录的, 但是在QLite里似乎没有提供自行更改platform的设置

**Comment by Vi-brance** [comment]
> 5/17, 还是有同样的问题, 我用icqq把platform改成2是可以登录的, 但是在QLite里似乎没有提供自行更改platform的设置

因为现在除了watch协议都无法使用二维码登录，且部分协议接收消息的功能并不完全，所以我没有开放这个选项，暂时的解决方法只能直接修改扩展源代码，不过等icqq修复后应该也没太大必要了

**Comment by eric2788** [comment]
同樣問題，目前確實只能使用watch協議（我自己基於miraigo寫的qq機器人目前也能用watch協議才能成功登陸）
目前確實是掃碼和帳戶密碼都無法登陸
掃碼出現如下
![image](https://github.com/Vi-brance/vscode-qlite/assets/6276840/0fadb428-5acb-4921-abd2-8ee0c9a30502)
帳戶密碼出現如下
<img width="455" alt="image" src="https://github.com/Vi-brance/vscode-qlite/assets/6276840/79e19f14-78ba-4bca-b26f-abe89ace4f19">

**Comment by zhuxixi** [comment]
同样的问题

**Comment by Vi-brance** [comment]
新版本中已开放协议选项，建议使用`old_Android`协议登录使用，若还有`Error Code: 45`的错误，暂时只能等待icqq的更新修复

**Comment by eric2788** [comment]
> 新版本中已开放协议选项，建议使用`old_Android`协议登录使用，若还有`Error Code: 45`的错误，暂时只能等待icqq的更新修复

使用old android直接沒有反應，卡住登陸中
使用watch協議會出現二維碼，但我還沒開始掃，它就直接timeout顯示登陸失敗了？

**Comment by Vi-brance** [comment]
> > 新版本中已开放协议选项，建议使用`old_Android`协议登录使用，若还有`Error Code: 45`的错误，暂时只能等待icqq的更新修复
> 
> 使用old android直接沒有反應，卡住登陸中 使用watch協議會出現二維碼，但我還沒開始掃，它就直接timeout顯示登陸失敗了？
> 
> 下面是掃完之後顯示失敗 <img alt="image" width="567" src="https://user-images.githubusercontent.com/6276840/254209179-babb2dc8-05e2-4954-ba4d-ac910100f02d.png">

最新版本中没有watch协议，请更新到最新版重试

**Comment by eric2788** [comment]
> > > 新版本中已开放协议选项，建议使用`old_Android`协议登录使用，若还有`Error Code: 45`的错误，暂时只能等待icqq的更新修复
> > 
> > 
> > 使用old android直接沒有反應，卡住登陸中 使用watch協議會出現二維碼，但我還沒開始掃，它就直接timeout顯示登陸失敗了？
> > 下面是掃完之後顯示失敗 <img alt="image" width="567" src="https://user-images.githubusercontent.com/6276840/254209179-babb2dc8-05e2-4954-ba4d-ac910100f02d.png">
> 
> 最新版本中没有watch协议，请更新到最新版重试

我用的這個版本， release 最新也是這個版本
<img width="329" alt="image" src="https://github.com/Vi-brance/vscode-qlite/assets/6276840/7b143e19-ac71-4fa4-88fa-c1756b57aa01">

**Comment by Vi-brance** [comment]
> 我用的這個版本， release 最新也是這個版本 <img alt="image" width="329" src="https://user-images.githubusercontent.com/6276840/254439021-7b143e19-ac71-4fa4-88fa-c1756b57aa01.png">

建议先用`old_android`协议尝试登录，打开`devtool`查阅是否有报错信息，最新版本不建议使用`watch`协议

**Comment by eric2788** [comment]
> > 我用的這個版本， release 最新也是這個版本 <img alt="image" width="329" src="https://user-images.githubusercontent.com/6276840/254439021-7b143e19-ac71-4fa4-88fa-c1756b57aa01.png">
> 
> 建议先用`old_android`协议尝试登录，打开`devtool`查阅是否有报错信息，最新版本不建议使用`watch`协议

昨晚卡住沒反應，但是今天成功了
然後想問的是自定義theme哪裡設置？之前用的extension vscode-qq是可以設置的，因為目前的theme太顯眼

**Comment by Vi-brance** [comment]
> > 建议先用`old_android`协议尝试登录，打开`devtool`查阅是否有报错信息，最新版本不建议使用`watch`协议
> 
> 昨晚卡住沒反應，但是今天成功了 然後想問的是自定義theme哪裡設置？之前用的extension vscode-qq是可以設置的，因為目前的theme太顯眼

自定义theme功能在开发途中，详见 #21 ，由于我几乎没有开发聊天界面的经验，所以不知道如果需要自定义theme需要提供哪些接口，欢迎在 #21 讨论&协助开发

**Comment by Vi-brance** [comment]
v1.5.2中已更新icqq，应该会大幅改善登录问题，若无问题将关闭此issue
