### ISSUE TITLE
无法打开chromium使用滑动验证码登录

### ISSUE THREAD

**Issue by LierJeo** [Vi-brance/vscode-qlite#16]
点击登录按钮未响应

日志如下
![image](https://github.com/Vi-brance/vscode-qlite/assets/38379794/456c7080-ef60-4479-bfbe-dc00c2f9f379)
以收到滑动验证码但无法打开页面验证

**Comment by Vi-brance** [comment]
这个问题说明你的电脑没有安装chromium框架，目前此扩展只支持唤起chromium进行自动化操作，如果你的电脑中没有chromeium框架的浏览器（如Edge、Chrome），可以尝试下载一个单独的框架。

我将尝试修改自动化策略，使其支持更多类型的浏览器，并在下一版本中修复它。

**Comment by Vi-brance** [comment]
我看了下自动化操作的puppteer包似乎只支持chrome系浏览器，而且似乎没有其他具有相同功能的支持多类型浏览器的npm包，我暂时添加一个备用接口手动填写登录信息吧。

**Comment by LierJeo** [comment]
但我确实不仅有edge也有chrome，使用taka大佬的插件可以顺利唤起验证页。
今天更新后QLite登录依旧报相同错误

**Comment by Vi-brance** [comment]
> 但我确实不仅有edge也有chrome，使用taka大佬的插件可以顺利唤起验证页。 今天更新后QLite登录依旧报相同错误

这个报错信息有两个可能的原因，其一是没有对应模块，但扩展是被打包过的，模块应该都被正常加载了；其二是缓存路径有问题，你能进入`C:\Users\zktt\.cache\puppeteer`这个路径查看是否有相关文件吗？这是我测试时的对应路径的文件目录结构，请与你的目录比对是否有区别：
```
puppteer
└─chrome
    └─win64-1108766
        └─chrome-win
            ├─locales
            └─MEIPreloa
```
其次也有可能缺少对目录的控制权限，请查看`.cache`文件夹`属性`的`安全`选项卡，确认是否具有对此目录的完全控制权。

**Comment by LierJeo** [comment]
我的.cache目录下没有pupeteer文件夹
![image](https://github.com/Vi-brance/vscode-qlite/assets/38379794/06e69fbc-8a02-4f10-a0b5-e2d730e3eeaf)

**Comment by Vi-brance** [comment]
> 我的.cache目录下没有pupeteer文件夹 ![image](https://user-images.githubusercontent.com/38379794/238529646-06e69fbc-8a02-4f10-a0b5-e2d730e3eeaf.png)

好的，我发现问题所在了，似乎这个包并不会在用户端部署chromium，我将尝试让其打开本地的浏览器进行验证
