### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by youlan2333** [Vi-brance/vscode-qlite#18]
[禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Error Code: 45
![image](https://github.com/Vi-brance/vscode-qlite/assets/64688148/c674f65f-aa44-4bcc-9392-19080a43af93)

所以还是爆破腾讯大楼（删除）罢

**Comment by Vi-brance** [comment]
icqq那边添加了一个旧版安卓手机设备似乎可以解决这个问题，我将把更换登录设备的选项添加到扩展中，这样在触发这个问题时可以自己解决

**Comment by youlan2333** [comment]
好~

**Comment by Vi-brance** [comment]
已更新，等待你的反馈ing

**Comment by youlan2333** [comment]
> 已更新，等待你的反馈ing

还是不行（悲）

**Comment by Vi-brance** [comment]
> > 已更新，等待你的反馈ing
> 
> 还是不行（悲）

你尝试过更换登录设备吗？

**Comment by youlan2333** [comment]
> > > 已更新，等待你的反馈ing
> > 
> > 
> > 还是不行（悲）
> 
> 你尝试过更换登录设备吗？
死活不行，两个qq号都试过了，小号在完成验证码之后还是显示版本低
![image](https://github.com/Vi-brance/vscode-qlite/assets/64688148/c1af674f-dc50-43b6-b406-e2039a847466)

**Comment by Vi-brance** [comment]
我测试用的账号可以登录，可能是账号问题吧，这我就无能为力了😔

**Comment by youlan2333** [comment]
> > > 已更新，等待你的反馈ing
> > 
> > 
> > 还是不行（悲）
> 
> 你尝试过更换登录设备吗？

寄
![image](https://github.com/Vi-brance/vscode-qlite/assets/64688148/d2cbe3ea-85b1-4980-b2e1-7d0362327155)

**Comment by youlan2333** [comment]
> 我测试用的账号可以登录，可能是账号问题吧，这我就无能为力了😔

...好吧😭

**Comment by Vi-brance** [comment]
@youlan2333 若你还在使用此扩展，请确认在最新版中是否还会有此issue中描述的问题
