### ISSUE TITLE
登录出现错误

### ISSUE THREAD

**Issue by dishiyicijinqiu** [Vi-brance/vscode-qlite#19]
![image](https://github.com/Vi-brance/vscode-qlite/assets/9463907/39d90269-024f-4a2b-9ba2-48fd65291997)
咋弄，这密码肯定是没错的，我换了一个号还是提示这，我换了oldandroid提示这个额，我用默认的android，提示的是这个版本过低

**Comment by Vi-brance** [comment]
账号密码我都是直接传值没有修改的，所以不会有问题，也与协议无关，你可以排查下是否是你改了密码or账号输错了

**Comment by dishiyicijinqiu** [comment]
meiyou 解决，我已经卸载了，始终提示账号密码不对，只能卸载了
