### ISSUE TITLE
漫游表情显示不出来

### ISSUE THREAD

**Issue by NineMeowICT** [Vi-brance/vscode-qlite#2]
如图
![屏幕截图_20230107_150421](https://user-images.githubusercontent.com/115801669/211138834-afe3320d-a4cd-44dc-8cec-f84e0c192e8a.png)
尝试多次结果相同
日志（Level=trace）无异常

**Comment by Vi-brance** [comment]
由于重新分配了界面调用的函数，获取漫游表情的函数在整理时被删掉了，后续会想办法加回来的
