### ISSUE TITLE
每次登录都会生成新的device.json

### ISSUE THREAD

**Issue by pkoukk** [Vi-brance/vscode-qlite#20]
每次登录log都会输出 创建了新的设备文件
查看了一下device.json，确实发生了改变

**Comment by Vi-brance** [comment]
这是icqq初始化时决定的，扩展本身没有特意为之，会有什么影响吗

**Comment by pkoukk** [comment]
频繁更换device信息触发风控的概率比较高，容易被235 😂

**Comment by Vi-brance** [comment]
我翻阅了icqq的源码，模块通过`require`加载的device文件，他为什么不能好好用`fs`呢🤨

**Comment by Vi-brance** [comment]
issue已发送，等待模块作者解决ing

**Comment by pkoukk** [comment]
以前没有这个问题，可能是vscode更新了插件的运行权限级别导致的
本地测试把icqq的require切换到fs后可以正常读取，发了PR给icqq 😂

**Comment by Vi-brance** [comment]
pr已merge，preview版将更新icqq版本并发布，此issue终结
