### ISSUE TITLE
消息页面停止刷新的bug

### ISSUE THREAD

**Issue by RainEffect** [Vi-brance/vscode-qlite#25]
RT，聊天窗口在打开并持续5秒之后，将会彻底停止刷新，如：无法接收/发送消息/表情……
我不清楚这个是否只有我自己触发了这个bug，所以还是留个issue……

VisualStudioCode的版本为1.80.2，qlite扩展为当前市场内的最新版v1.5.2。
使用qlite扩展所登录的QQ账号一共971个好友，243个群，8个频道。
该账号基本上每分钟会收到大约300-40条来自于不同的好友/群/频道的消息。
为了不影响其他端的登录状态(如我本地的QQPC，在服务器挂的Mirai等)，我在使用本扩展时使用的设备类型为"iMac"。

以上为对当前使用环境的大致说明，希望可以确认缘由。

**Comment by RainEffect** [comment]
![image](https://github.com/Vi-brance/vscode-qlite/assets/14258727/35a125e0-616b-4101-87b2-06ed9daf9efe)

**Comment by Vi-brance** [comment]
先尝试更换其它可用协议（把其它端的账号先下线用于此扩展进行测试），如果解决那应该是`iMac`协议问题，这个问题由`icqq`库处理，我无法解决；若没解决则先等其他人是否有类似问题，若没有我猜测可能是消息频率过高导致（基于功能考量，本扩展的同步效果并不是很好）。

**Comment by RainEffect** [comment]
我也猜测到可能是频率过高的问题，后续在有空的时候我会另外使用一个bot账号进行多次测试。

**Comment by statementreply** [comment]
同样聊天窗口打开几秒钟后，就收不到新的消息，但插件边栏会继续更新没打开的群的消息条数。协议是默认的 Android。

![zopfli_屏幕截图 2023-07-31 230220](https://github.com/Vi-brance/vscode-qlite/assets/3018812/9ca4ddcb-4ffd-414b-880e-d961125d81ac)

**Comment by Vi-brance** [comment]
版本已更新
