### ISSUE TITLE
看上去登录失败, 但是看控制台像是登录成功

### ISSUE THREAD

**Issue by Wing0v0** [Vi-brance/vscode-qlite#26]
![image](https://github.com/Vi-brance/vscode-qlite/assets/49347091/498260bc-8de7-4e8a-bfd7-ffb3bafecbec)
好友, 用户名等信息都加载出来了?

**Comment by Vi-brance** [comment]
描述下你的登录过程，还有提供下`.../User/user-name/.qlite/login-record.json`文件的信息（其中有账号和密码记录，可以打码）

**Comment by Wing0v0** [comment]
尝试过了, 一开始选的Android协议, 发现把我手机登录状态顶下去了
然后改成其他方式也是一样

**Comment by Vi-brance** [comment]
好像并不是我这边的问题，你之前是不是用过这个扩展，把`login-record.json`文件删除后重试一次应该就可以了。

**Comment by Wing0v0** [comment]
对的, 之前用过该拓展,发现无法登录, 现在可以正常登录了
我把.qlite文件夹删除了
