### ISSUE TITLE
在接收消息时显示的昵称错误

### ISSUE THREAD

**Issue by RainEffect** [Vi-brance/vscode-qlite#28]
RT，此问题主要为群名片/用户昵称两者之间出现了错误。

![image](https://github.com/Vi-brance/vscode-qlite/assets/14258727/e5c0e818-2a77-482f-b238-a71d4993a58d)
我一开始的判断以为：在打开群聊时，群历史聊天记录将会以“群名片”显示，后续收到的新消息将会以“用户昵称”显示……

但……直到我自己发了一次消息……
![image](https://github.com/Vi-brance/vscode-qlite/assets/14258727/ecea5709-112f-491c-bfe2-4b2b9e615da8)
(注:此处我仅发送了一次，但弹出了两次的消息，且显示的昵称均不相同)
嗯，可能需要从底层确认错误原因。

**Comment by Vi-brance** [comment]
下一版本修复

**Comment by Vi-brance** [comment]
更新扩展，测试是否还有上述问题，若无则此issue over。

**Comment by statementreply** [comment]
> 在打开群聊时，群历史聊天记录将会以“群名片”显示，后续收到的新消息将会以“用户昵称”显示

更新 1.5.3 后仍然存在这个问题

> 仅发送了一次，但弹出了两次的消息，且显示的昵称均不相同

新版自己发出的群消息显示一次，显示名字为用户昵称

**Comment by Vi-brance** [comment]
可能是接口有更新，我再看看

**Comment by Vi-brance** [comment]
版本已更新
