### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by zhuoyandedandan** [Vi-brance/vscode-qlite#29]
![image](https://github.com/Vi-brance/vscode-qlite/assets/20151169/1620ac3d-3d2a-4b93-940a-976f11d3e474)报了这个提示
![image](https://github.com/Vi-brance/vscode-qlite/assets/20151169/c9051ecc-d789-4254-87ef-999d3798f3c4)

**Comment by Vi-brance** [comment]
参考 #26 新版本更新了记录文件，不支持久文件的识别，删除 `.qlite/login-record.json` 文件重试
