### ISSUE TITLE
切换账号时出现报错

### ISSUE THREAD

**Issue by RainEffect** [Vi-brance/vscode-qlite#31]
RT，在使用内置默认的账号切换功能进行当前登录QQ切换时，控制台出现了报错。
虽该报错并不影响账号实际切换情况和功能使用，但可能会影响到后续功能开发。

切换账号功能：
![image](https://github.com/Vi-brance/vscode-qlite/assets/14258727/9c2526e7-ef31-4c1a-9380-70ea7e05fe8f)

报错提示：
![image](https://github.com/Vi-brance/vscode-qlite/assets/14258727/e8c869e2-3ebc-4785-89c6-c36bfd0b5463)

**Comment by RainEffect** [comment]
v1.5.4 报错依然存在，在本问题出现新的报错或修复前，暂时保留该issue。

**Comment by RainEffect** [comment]
当前BUG: 可重复点击同一个账号进行登录，消息栏会在登录后收到第一条消息时才刷新。
![image](https://github.com/Vi-brance/vscode-qlite/assets/14258727/c33e5d4e-cc21-4cbd-bd45-465ba6df514c)

**Comment by Vi-brance** [comment]
> 当前BUG: 可重复点击同一个账号进行登录，消息栏会在登录后收到第一条消息时才刷新。 ![image](https://user-images.githubusercontent.com/14258727/258004533-c33e5d4e-cc21-4cbd-bd45-465ba6df514c.png)

此bug已修复，若无其它问题可结束此issue
