### ISSUE TITLE
设置更新后的错误判断检查

### ISSUE THREAD

**Issue by RainEffect** [Vi-brance/vscode-qlite#33]
RT，因为修改了qlite.platform的type，且没对其进行向前兼容，以至于更新后出现无法登录的情况。

发生错误的地方：
![image](https://github.com/Vi-brance/vscode-qlite/assets/14258727/7e05be50-5c66-4ae6-a882-d90630d9fc83)

无法登录错误报告：
![image](https://github.com/Vi-brance/vscode-qlite/assets/14258727/7fe86414-fde9-42e0-ad72-0d85241fd811)

**Comment by Vi-brance** [comment]
这项设置应该是下拉框而不用在setting.json中编辑，通常情况下不会设置为无法识别的登录协议名。

**Comment by RainEffect** [comment]
因为历史版本的该设置项为通过"数字"作为区分不同协议名，而v1.5.4开始是通过"协议"名称进行区分，
所以在从v1.5.3升级到v1.5.4时会出现无法登录的报错。

[Commit:更换登录协议设置配置内容[ba6cd45]](https://github.com/Vi-brance/vscode-qlite/commit/ba6cd45ec149ae1eb092a10220ea35a331173277)

**Comment by Vi-brance** [comment]
> 因为历史版本的该设置项为通过"数字"作为区分不同协议名，而v1.5.4开始是通过"协议"名称进行区分， 所以在从v1.5.3升级到v1.5.4时会出现无法登录的报错。
> 
> [Commit:更换登录协议设置配置内容[ba6cd45]](https://github.com/Vi-brance/vscode-qlite/commit/ba6cd45ec149ae1eb092a10220ea35a331173277)

下一版本更新内容会添加更换提示，但不打算在代码上进行兼容

**Comment by RainEffect** [comment]
并非兼容，而是检查原有设置，如果设置项是数字(基于老版本更新)则自动替换成对应字符串

**Comment by Vi-brance** [comment]
> 并非兼容，而是检查原有设置，如果设置项是数字(基于老版本更新)则自动替换成对应字符串

新版添加了设置检查，但最好的办法还是删除原有设置

**Comment by Vi-brance** [comment]
> 按正常逻辑而言，功能更新前若非出现和前代版本完全不匹配的情况（指需要卸载并删除所有数据的情况），一般都需要针对从老版本更新到新版本进行一个支持（此处的支持不仅仅是配置），因为不是所有的使用者都是绝对的开发人员，包括我。
> 
> 以个人曾经的开发经验来说，自然是在确认是从v1.5.3及其以前版本为基础更新的话，最好是对相关配置进行自动更新和替换（一般此检查机制保留一个大版本/三个自然月），直到超过一定期限后移除。这种方式属于是对于用户来说最为无感的版本更替。

感谢建议，倘若下次更新时有类似改动我会采用你描述的方式进行解决。

此扩展的用户群体默认为有编程基础（个人认为*完全*没有编程基础的人很大概率不会用到VSCode这样的编辑器），加之此扩展是个人维护的小扩展，一些简单的小问题没有为*零基础*的用户进行深度考虑，相信大部分用户能够自己解决（当然还是欢迎像你一样对此进行反馈）。

其次是此扩展的开发目的。此扩展的前身，即 **vscode-qq** ，开发出来的目的是为了解决linux用户没有较好的QQ客户端的痛点，以及一小部分win用户厌恶官方QQ臃肿的空间占用问题。而在此扩展开始开发后的一小段时间后，QQnt宣布公测，linux端用户的痛点已经解决，我的开发重心就转移到为轻度使用QQ的用户（仅使用以聊天为中心的一小部分功能）和经常使用VSCode的程序员服务。这就是我没有*贴心地*为用户作设置过渡的主要原因。
