### ISSUE TITLE
部分协议登录报错卡死

### ISSUE THREAD

**Issue by RainEffect** [Vi-brance/vscode-qlite#38]
RT，部分协议在更新到v1.5.4版本后登录会报错卡死，但触发条件比较苛刻。

报错内容：
![image](https://github.com/Vi-brance/vscode-qlite/assets/14258727/68bf8392-194b-4cf9-bb7f-5d3bafc06991)

触发方式：
在重新启动vscode初次使用Qlite前，设定Platform为iMac，iPad，Tim其中任意一个，进行登录。

**Comment by Vi-brance** [comment]
部分协议当前版本并未提供支持，非开发环境不要使用

**Comment by Vi-brance** [comment]
经测试目前可用且功能完整的协议只有 `Android` ，如果有特殊协议需求请等待 `icqq` 更新
