### ISSUE TITLE
打开设置页存在错误

### ISSUE THREAD

**Issue by Wing0v0** [Vi-brance/vscode-qlite#39]
# 截图
![1691373277321](https://github.com/Vi-brance/vscode-qlite/assets/49347091/e25e151f-5eb9-449d-a5fb-f09893cdcafc)

# 具体操作
1. 卸载插件
2. 在插件目录删除插件遗留文件, 同时删除User/.qlite文件夹
3. 重新安装插件

**Comment by Vi-brance** [comment]
#33 已提及此问题，将扩展相关设置恢复默认即可。
