### ISSUE TITLE
期望加入“显示表情/图片缩略图”的功能

### ISSUE THREAD

**Issue by NineMeowICT** [Vi-brance/vscode-qlite#4]
如题，现在表情和图片都只能根据原分辨率显示，很占聊天版面；
如果能够默认显示缩略图，需要时查看大图（在下方标注大图直链也行），会比较好。

**Comment by Vi-brance** [comment]
消息栏图片缩略其实写了个简单的，但是似乎没什么效果  
查看原图的话目前的方法是可以把聊天框里的图片拖到其他浏览器中显示

**Comment by NineMeowICT** [comment]
> 消息栏图片缩略其实写了个简单的，但是似乎没什么效果 查看原图的话目前的方法是可以把聊天框里的图片拖到其他浏览器中显示
我看发出去的消息里，图片无法选中，还以为复制不了，原来是拖到浏览器里就行了，谢谢你的回答！
期待新功能！

**Comment by NineMeowICT** [comment]
> 消息栏图片缩略其实写了个简单的，但是似乎没什么效果 查看原图的话目前的方法是可以把聊天框里的图片拖到其他浏览器中显示

还有就是，顺带一提，v1.2.6表情栏更新之后，现在打开漫游表情栏，本来的顺序是从上到下对应从新到旧，现在相反了，而默认打开后的表情栏视图位置是在最上，还得用滑块划到最下以使用最新收藏的漫游表情，感觉用起来不太顺手，希望可以优化一下（比如弄个正序反序的设置按钮？）

**Comment by Vi-brance** [comment]
V1.2.7已支持图片缩放和双击放大功能

**Comment by NineMeowICT** [comment]
> V1.2.7已支持图片缩放和双击放大功能

刚发出去的图片不会显示为缩略图，而仍旧以大图形式显示，需要关闭标签页后重新打开才能正常显示缩略图。
