### ISSUE TITLE
UI方面，已发现bug总结

### ISSUE THREAD

**Issue by NineMeowICT** [Vi-brance/vscode-qlite#6]
1、vscode在非活跃窗口情况下接收多条信息，将其唤起之后，左侧消息概况栏刷新时，出现频繁闪烁的情况
2、点击撤回后显示的系统消息，被撤回的消息高亮显示效果差（高亮不明显），而且出现闪烁状况，经取色器确认是在多个相近的颜色之间频繁切换所致

可能不算bug的小问题：消息发送框的「发送」按钮左侧还有一大条空白区域，虽然一般情况影响不大，不过在打多行文本时，有时候因为这个挡住会有点不舒服，希望能把这一条去掉，并将发送按钮半透明化？

**Comment by Vi-brance** [comment]
收到，感谢反馈！

**Comment by Vi-brance** [comment]
关于发送按钮旁的空白区域，在页面中发送按钮是独占一行的，所以左侧会有空白，若是发送文本行数较多，可以尝试拖动输入框上方的分割线，增大输入框的显示比例

**Comment by Vi-brance** [comment]
关于撤回消息的高亮显示问题，使用的是最简单的背景颜色线性变化，因为我也没接触过这个动画怎么写，所以暂时先按原扩展的处理方式解决，有大佬能美化一下就更好了（

**Comment by Vi-brance** [comment]
关于消息栏频繁闪烁的问题，我不太清楚你这个问题的触发情况，有能力复现的话希望你能复现一下这个问题

**Comment by NineMeowICT** [comment]
> 关于消息栏频繁闪烁的问题，我不太清楚你这个问题的触发情况，有能力复现的话希望你能复现一下这个问题


https://user-images.githubusercontent.com/115801669/212463482-833a4a36-0f26-45db-bca5-300ee2cb075e.mp4

如视频中左侧消息栏状况

**Comment by NineMeowICT** [comment]
私聊的图片问题没有完全解决，自己发送出去的图片，自己一开始是看不到的，必须关闭聊天标签页重新打开，才会加载出来

**Comment by Vi-brance** [comment]
我尝试按你描述的方法测试时没有出现这个问题，重启是否能解决呢？

**Comment by NineMeowICT** [comment]
> 我尝试按你描述的方法测试时没有出现这个问题，重启是否能解决呢？

从最开始的版本到现在一直有这个问题，重启无效，更改网络环境无效，更换硬件驱动无效，升级vscode无效

**Comment by Vi-brance** [comment]
你的vscode安装环境是什么？

**Comment by NineMeowICT** [comment]
> 你的vscode安装环境是什么？

安装环境？哪方面的？可以举个例吗

**Comment by NineMeowICT** [comment]
唔，更新1.3.2之后插入不了表情了

**Comment by Vi-brance** [comment]
> > 你的vscode安装环境是什么？
> 
> 安装环境？哪方面的？可以举个例吗

我开发测试的环境是win11的vscode桌面端，版本信息如下
![image](https://user-images.githubusercontent.com/82794754/212475021-e9c0c2c1-fddc-472c-ac03-35288d0bd08e.png)

**Comment by NineMeowICT** [comment]
> > > 你的vscode安装环境是什么？
> > 
> > 
> > 安装环境？哪方面的？可以举个例吗
> 
> 我开发测试的环境是win11的vscode桌面端，版本信息如下 ![image](https://user-images.githubusercontent.com/82794754/212475021-e9c0c2c1-fddc-472c-ac03-35288d0bd08e.png)

@Vi-brance 
![image](https://user-images.githubusercontent.com/115801669/212476041-07823ed4-0719-4bae-acc5-a42bc9b80ff8.png)

**Comment by NineMeowICT** [comment]
换行还是有问题，shift+enter换行之后发送出去的消息，实质上仍旧在一行上

**Comment by Vi-brance** [comment]
> > > > 你的vscode安装环境是什么？
> > > 
> > > 
> > > 安装环境？哪方面的？可以举个例吗
> > 
> > 
> > 我开发测试的环境是win11的vscode桌面端，版本信息如下 ![image](https://user-images.githubusercontent.com/82794754/212475021-e9c0c2c1-fddc-472c-ac03-35288d0bd08e.png)
> 
> @Vi-brance ![image](https://user-images.githubusercontent.com/115801669/212476041-07823ed4-0719-4bae-acc5-a42bc9b80ff8.png)

看你打开侧边栏时好像扩展一直在加载（即上方的蓝色进度条）？正常来说应该不会有一直刷新的情况

**Comment by Vi-brance** [comment]
@NineMeowICT 好久不见！你现在使用这个扩展还有上述问题吗？如果有请告诉我

**Comment by NineMeowICT** [comment]
> @NineMeowICT 好久不见！你现在使用这个扩展还有上述问题吗？如果有请告诉我

辛苦了！
我现在转用Icalingua++了，所以qlite用的比较少，昨天试了一下，上述问题没有出现

不过视频和语音还是无法正常播放，左边栏右键联系人的「查看资料」点击后也没有反应

**Comment by Vi-brance** [comment]
感谢反馈！上述功能都在实现目标内，但开发速度可能较慢，敬请期待！
