### ISSUE TITLE
提示QQ版本过低，无法登陆

### ISSUE THREAD

**Issue by MistEO** [Vi-brance/vscode-qlite#8]
前几天还正常的，感觉腾讯又改了什么东西。vscode-qq 那边也有相关的问题 https://github.com/takayama-lily/vscode-qq/issues/83 ，但我把 1-5 都试了一遍没一个能用的 orz，希望大大能适配一下，非常感谢_(:з」∠)_

![image](https://user-images.githubusercontent.com/18511905/219682839-76e69670-f2c8-404e-8dde-950150988ecd.png)

**Comment by Vi-brance** [comment]
我开发过程中也遇到过相同的问题，由于oicq为了保证不同账号的设备信息不同，而同一个账号在不同设备登陆时生成的设备一致，生成的设备信息是基于登陆账号的固定信息，而该错误发生是因为当前设备被腾讯管控，因此只需要修改你的登陆设备信息即可。
具体方法则是进入`C:\Users\用户名\AppData\Roaming\Code\User\globalStorage\vi-brance.vscode-qlite`目录下，进入你登陆失败的账号的文件夹，里面会有一个名为`device-你的QQ账号.json`的设备信息文件，推荐修改其中的`imei`段，更改末端数字后保存，重新登陆即可生效。
这个问题是oicq自身的bug，已经有人向开发者提issue了，我这个方法也只是临时的，若清除了账号的设备信息，它会重新生成原先的信息，但是腾讯的管控似乎只是临时的，所以一段时间后原先的设备信息应该会恢复登录能力。

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/219871632-1b6a8012-f367-47d1-a24c-b244d06a7beb.png)


试了一下又变成了这样的提示 orz

在 go-cqhttp 那边捞了个能登陆的 device 信息，把 oicq 对应字段照着改了下，结果还是不行_(:з」∠)_

**Comment by Vi-brance** [comment]
不好意思现在才注意到你的回复，我在oicq的开发文档中发现，你截图中的`Error Code`是滑动验证时的ticket输入错误导致，请确认一下你的滑动验证码是否复制完整，有无多余引号

**Comment by Ritchie1108** [comment]
倒是可以把协议换成
https://github.com/icqqjs/icqq

**Comment by Vi-brance** [comment]
我日常使用的qq没有上述问题，出现了也依据
> 我开发过程中也遇到过相同的问题，由于oicq为了保证不同账号的设备信息不同，而同一个账号在不同设备登陆时生成的设备一致，生成的设备信息是基于登陆账号的固定信息，而该错误发生是因为当前设备被腾讯管控，因此只需要修改你的登陆设备信息即可。 具体方法则是进入`C:\Users\用户名\AppData\Roaming\Code\User\globalStorage\vi-brance.vscode-qlite`目录下，进入你登陆失败的账号的文件夹，里面会有一个名为`device-你的QQ账号.json`的设备信息文件，推荐修改其中的`imei`段，更改末端数字后保存，重新登陆即可生效。 这个问题是oicq自身的bug，已经有人向开发者提issue了，我这个方法也只是临时的，若清除了账号的设备信息，它会重新生成原先的信息，但是腾讯的管控似乎只是临时的，所以一段时间后原先的设备信息应该会恢复登录能力。

这个方法解决了，所以我暂时不打算更换到icqq ~（主要还是希望oicq能更新）~

**Comment by Ritchie1108** [comment]
> 常使用的qq没有上述问题，出现了也依据
> 
> > 我开发过程中也遇到过相同的问题，由于oicq为了保证不同账号的设备信息不同，而同一个账号在不同设备登陆时生成的设备一致，生成的设备信息是基于登陆账号的固定信息，而该错误发生是因为当前设备被腾讯管控，因此只需要修改你的登陆设备信息即可。具体方法则是进入目录下，进入你登陆失败的账号的文件夹，里面会有一个名为的设备信息文件，推荐修改其中的段，更改末端数字后保存，重新登陆即可生效。这个问题是oicq自身的bug，已经有人向开发者提issue了，我这个方法也只是临时的，若清除了账号的设备信息，它会重新生成原先的信息，但是腾讯的管控似乎只是临时的，所以一段时间后原先的设备信息应该会恢复登录能力。`C:\Users\用户名\AppData\Roaming\Code\User\globalStorage\vi-brance.vscode-qlite``device-你的QQ账号.json``imei`
> 
> 这个方法解决了，所以我暂时不打算更换到ICQQ ~（主要还是希望oicq能更新）~

按照之前在群里其他协议相关作者的讨论, 他应该是没什么精力维护了

**Comment by Vi-brance** [comment]
这边正在尝试用go-cqhttp作核心协议库，这个库的活跃度较高，维护比较及时，但由于是go-lang实现，需要自己建立api连接到nodejs中，所以难度较大，等我把demo写出来吧（写不出来就只能作罢了）

**Comment by Vi-brance** [comment]
> 这边正在尝试用go-cqhttp作核心协议库，这个库的活跃度较高，维护比较及时，但由于是go-lang实现，需要自己建立api连接到nodejs中，所以难度较大，等我把demo写出来吧（写不出来就只能作罢了）

投降了🏳️，go-cqhttp的兼容比想象中困难，而且api相比oicq有比较大的区别，我还是更换到icqq吧（

**Comment by Vi-brance** [comment]
v1.3.9已更换协议到icqq，若没有其他恶性bug将关闭此issue

**Comment by katalinas** [comment]
登录提升>>
[禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Error Code: 45

**Comment by Vi-brance** [comment]
> 登录提升>> [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Error Code: 45

？？？我在icqq库中都没有找到`error code: 45`的报错信息，你这个报错信息是怎么产生的

**Comment by Wing0v0** [comment]
![image](https://user-images.githubusercontent.com/49347091/234162737-aaf08df7-6b6c-42ab-bd5e-9cac20d8eed1.png)

**Comment by Ritchie1108** [comment]
createClient的时候, platform 可以用 1

**Comment by RisingInIris2017** [comment]
> > 登录提升>> [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Error Code: 45
> 
> ？？？我在icqq库中都没有找到`error code: 45`的报错信息，你这个报错信息是怎么产生的

扩展版本 1.4.2，可以复现：
![image](https://user-images.githubusercontent.com/28519848/236144358-20c0e270-2c9f-4bef-973f-1118e9e70e13.png)

**Comment by Vi-brance** [comment]
在icqq的[这个issue](https://github.com/Vi-brance/vscode-qlite/issues/8)中也提到了你的问题，但似乎作者并没有回应如何解决，你可以关注下这个issue的进展

PS：v1.4时更改了保存文件的目录，现在生成的文件都在用户目录的`.qlite`文件夹中，更多扩展更新的信息可以查看[CHANGELOG](https://github.com/Vi-brance/vscode-qlite/blob/main/CHANGELOG.md)文件

**Comment by yyx2684264** [comment]
作者你好，今天登录我依然遇到了code:45的错误，同时我看了下隔壁icqq更新了一个版本，不知道是否有解决这个问题，麻烦作者尝试一下❤

**Comment by Vi-brance** [comment]
> 关于gocq这块，我qq机器人现在用的就是gocq，他们之前也遇到过登录问题，但是现在好像可以动态更新协议文件了，可以自动获取最新的设备协议文件，很好的解决了这个问题。 另外关于gocq这块我也有一些个人使用nodejs开发的经验，如果作者想要迁移到gocq平台的话我不知道我能不能给予一些帮助。

确实我也发现gocq对动态更新设备文件的功能非常吸引人，我之前有尝试过迁移gocq，但是由于它用golang编写，如果要使用nodejs则只能通过`websocket`或`http`的通信协议，这需要在扩展中自行构建可用的API接口，就便捷性而言自然是比不过nodejs支持的icqq的。

~~真正让我放弃gocq的原因是它缺少一些icqq（或者说原oicq）的部分api接口~~，我又重新翻了下gocq的文档，本来想列举下缺少的api接口的，现在一看似乎感觉没哪里有缺的（完全忘了之前为啥弃坑了）。

如果真要~~投奔~~gocq：我目前正在重新构建聊天页面及其相关的通信接口，如果改用gocq的话可能又要重写了（头皮发麻），我再研究下当时的弃坑原因吧，也许是之后的更新使其补充了一些api，如果没有api上的问题的话那得从API接口开始重构这个扩展，我不知道能不能行😂。

**Comment by yyx2684264** [comment]
我这边用的是websocket协议，用起来还是很方便，自己封接口的话主要工作在于提取CQ码，以及封装api调用接口，api调用接口的话可以封装一个通用调用api的函数，然后把常用的单独封装一下。
附件里有我自己写的一个messager模块（保存下来后改后缀名为js），封装了一些常用的收发功能，以及将CQ码转换为JSON对象。

但是为了每次发送的消息都能获取到反馈判断是否发送成功，程序中用了大量async/await设计，所以效率可能不太高，但是一般聊天使用还是完全足够了。

下面是使用方法的简单说明：

1.让gocq开启正向websocket服务

2.在项目代码中引入ws客户端
`var WebSocket = require("ws");`
`var ws = new WebSocket("ws://127.0.0.1:端口号");`

3.将接收到的数据传递给messager中的handler:
`ws.onmessage = async function (msg) {`
`                // console.log(msg.data);`
`                let MsgJSON = JSON.parse(msg.data);`
`                Messenger.MsgHandler(ws, MsgJSON);`
`               // 其他的处理函数`
`                其他处理函数(MsgJSON);`
`            }`

在通过以上的方法可以让每次传递过来的消息经过Messager模块，让messager模块进行处理（包括但是不限于判断是否需要定时撤回，消息是否发送成功），对于其他处理函数或者模块，直接调用Messager模块中的方法就可以了，比如发送消息，下载文件。

希望对你有所帮助，一起学习进步！

[Messenger.txt](https://github.com/Vi-brance/vscode-qlite/files/11439413/Messenger.txt)

**Comment by Vi-brance** [comment]
@yyx2684264 首先感谢你提出的建议，这对我开发扩展将非常有帮助，但是关于封装api方面，你可以简单阅读一下仓库的代码（我刚更新了仓库代码，其中的注释应该比较容易让你理解），其中调用到的api可能比你想象中的要多，为了方便后续维护和扩展，可能需要编写一个运行于nodejs的api库作为底层服务。而以我目前的开发能力而言不是不可能，只是相当困难罢。

当然，我也发现这段时间`oicq`系被QQ的协议变化搞得鸡犬不宁，`gocq`可能在稳定性上更胜一筹，但是在 [Stapxs-QQ-Lite-2.0](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0.wiki) 这个项目中，同时提供了`icqq`和`gocq`的协议支持，而`gocq`相较`icqq`有部分缺少的API接口（这就是我之前找到的差别），其中我认为 **影响最大** 的是无法获取私聊的历史消息，这对本扩展而言是一个非常重要的功能。

如果作为机器人的运行协议，稳定性无疑是最重要的，因为机器人需要长时间的运行，而且少有机器人会综合地用到协议中的所有接口，因此`gocq`才更受欢迎吧。而作为客户端的底层协议，稳定性可能就没有那么重要了，~~毕竟你不会全天都打开vscode吧，~~ 而为了尽可能实现QQ中尽可能多的功能，需要的API越多越完整，客户端的实用性才更好。

你的想法我先暂时保留，以后等目前的扩展较为稳定了或者oicq寄了 ~~（不是）~~ 我会尝试构建基于此协议的扩展的，当然如果你是大佬也可以fork我的仓库自己魔改（参考`icqq`之于`oicq`）。

**Comment by yyx2684264** [comment]
好的，有空我也去看看这两个库，为之后改进机器人做准备，期待你的更新。

**Comment by Vi-brance** [comment]
@yyx2684264 我之后在github上翻找了下相关项目，找到了正在维护的基于nodejs的gocq库，现在API的问题解决了，可惜获取私聊历史消息的功能依然缺失，gocq那边短时间内似乎并不打算添加这个功能。

我暂且还是保持基于icqq的开发，尽量统一接口，方便更换模块时进行适配，我也会关注gocq那边的消息（当然最好的结果还是让oicq活过来）。
